@baseURL = {{$dotenv BASE_URL}}
@apikey = {{$dotenv API_KEY}}

POST {{baseURL}} HTTP/1.1
x-api-key: {{apikey}}
Content-Type: application/json

{
    "text": "Olá, este é um exemplo de síntese de fala usando Kokoro.",
    "lang": "p",
    "voice": "pf_dora"
}